name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]   # deploy when you push to main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install deps
        run: flutter pub get

      # custom domain at root -> base-href "/"
      - name: Build web
        run: |
          flutter build web --release --web-renderer canvaskit --base-href "/"
          cp build/web/index.html build/web/404.html   # SPA routing fix

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          force_orphan: true
          cname: inssoftsolutions.in
