name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

# Run all shell commands inside your Flutter app folder
defaults:
  run:
    working-directory: insoft_app   # <= CHANGE if your app folder is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable web (idempotent)
        run: flutter config --enable-web

      - name: Flutter doctor (optional for debugging)
        run: flutter doctor -v

      - name: Install deps
        run: flutter pub get

      - name: Build web
        run: |
          flutter build web --release --web-renderer canvaskit --base-href "/"
          cp build/web/index.html build/web/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: insoft_app/build/web   # <= NOTE: path includes the folder
          force_orphan: true
          cname: inssoftsolutions.in
