name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # If you ever want to pin a version:
          # flutter-version: "3.24.x"

      - name: Enable web
        run: flutter config --enable-web

      - name: Install deps
        run: flutter pub get

      - name: Build web (custom domain -> base-href "/")
        run: |
          flutter build web --release --base-href "/"
          cp build/web/index.html build/web/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          force_orphan: true
          cname: inssoftsolutions.in
